name: Test

on:
  push:
    branches:
      - test

jobs:
  Test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'


      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - run: npm ci

      - run: npm run test
        name: Execute Unit tests

      - uses: actions/checkout@v3
      - name: Create an issue
        if: ${{ failure() }}
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          actor: ${{ github.actor }}
          test: duplicate
          sha: ${{ steps.AWS.outputs.GITHUB_SHA_SHORT }}
          error: ${{ steps.mvn_test_error.outputs.msg }}
          error_short: ${{ steps.mvn_test_error_short.outputs.msg }}
        with:
          assignees: ${{ github.actor }}
          update_existing: true
          search_existing: open

      #      - name: TestFailed
      #        if: ${{ failure() }}
      #        uses: devops-infra/action-commit-push@master
      #        with:
      #          github_token: ${{ secrets.GITHUB_TOKEN }}
      #          commit_prefix: ${{ github.event.head_commit.message }} Show-stopper TestFailed


      - name: pull-request
        if: ${{ success() }}
        uses: repo-sync/pull-request@v2
        env:
          GITHUB_TOKEN: ${{ secrets.MYWORKFLOW  }}
        with:
          GITHUB_TOKEN: ${{ secrets.MYWORKFLOW  }}
          source_branch: "test"
          destination_branch: "main"
          pr_title: ${{ github.event.head_commit.message }}
          pr_body: ${{ github.event.head_commit.message }}
          pr_label: "Staging,TestsPassed"
          pr_assignee: "damouu"